#!/bin/bash
# primary menu script

function diskspace {
  clear
  df -k
}

function whoseon {
  clear 
  who
}

function memusage {
  clear
  cat /proc/meminfo

}

function menu {
  clear
  echo
  echo -e "\t\t\tSystem Admin Menu\n"
  echo -e "\t1. Display disk space\n"
  echo -e "\t2. Display logged on users\n"
  echo -e "\t3. Display memory usage\n"
  echo -e "\t0. Exit program\n\n"
  echo -en "\t\tEnter option: "
  read -n 1 option
}

while [ 1 ]
do 
  menu
  case $option in
  0) 
    break ;;
  1)
    diskspace ;;
  2)
    whoseon ;;
  3)
    memusage ;;
  *)
    clear
    echo "sorry, wrong selection";;
  esac
  echo -en "\n\n\t\tHit any Key to continue"
  read -n 1 line
done
clear

