#!/bin/bash
# extracting command line options and values with getopt

set -- `getopt -q ab:c "$@"`

while [ -n "$1" ]
do
  case "$1" in
  -a) echo "found -a option" ;;
  -b) param="$2"
      echo "found -b option, with parameter value $param" 
      shift ;;
  -c) echo "found -c option" ;;
  --) shift
      break ;;
  *) echo "$1 is not an option";;
  esac
  shift
done

count=1
for param in "$@"
do 
  echo "parameter #$count: $param"
  count=$[ $count + 1 ]
done

# $ ./test18 -ac
