#!/bin/bash
# extracting command line options as parameters

while [ -n "$1" ]
do
  case "$1" in
  -a) echo "found -a option" ;;
  -b) echo "found -b option" ;;
  --) shift
      break ;;
  *) echo "$1 is not an option";;
  esac
  shift
done

count=1
for param in $@
do 
  echo "parameter #$count: $param"
  count=$[ $count + 1 ]
done
