#!/bin/bash
# testing job control

echo "this is a test program $$"
count=1
while [ $count -lt 10 ]
do 
  echo "loop #$count"
  sleep 10
  count=$[ $count + 1 ]
done
echo "this is the end of the test program."

